### ISSUE TITLE
v0.8.0 CLI gets detected as malicious by CrowdStrike antivirus

### ISSUE THREAD

**Issue by mike1808** [nikitabobko/AeroSpace#124]
I upgraded from from v0.7.1 and CLI started getting marked as malicious by CrowdStrike corporate antivirus.
This ticket is just FYI for others if they face issues.
I am not sure if it's possible to fix or what exactly caused it.

**Comment by kdnk** [comment]
FYI: I've got the same report from CrowdStrike as well after installing v0.8.0.
v.0.7.1 is working well through.

**Comment by nikitabobko** [comment]
I think it's because I started using Swift package manager instead of Xcode to build the CLI b58b10882e0df4626d444c0ddc3f54456442a6be

Xcode automatically signs the binary, but with Swift package manager I need to sign it manually. I guess that if I add signing to the pipeline, CrowdStrike will be happy

**Comment by nikitabobko** [comment]
Should be fixed in 0.8.1. It'd be cool if you could verify it, I don't use CrowdStrike

**Comment by mike1808** [comment]
Thanks. It's not marked as malicious anymore.

**Comment by dlvhdr** [comment]
yup happening to me as well
