### ISSUE TITLE
battery life?

### ISSUE THREAD

**Issue by mrasputin** [nikitabobko/AeroSpace#128]
I wonder if implementation using virtual workspace won't decrease battery life. With native workspaces macOS is capable to optimize the power consumption of apps by "freezing" their rendering (which can be observed with yabai + SIP/animations disabled), which I'm guessing could not be the case for virtual workspace, as the apps remain on the same native workspace, but hidden in the corner. Curious if this has already been considered/measured?

**Comment by nikitabobko** [comment]
WWDC 2013 https://youtu.be/lyXdH5JjMLI?feature=shared&t=981 (16:21), Apple claimed that energy consumption only happens when the window is visible, so it's not based on whether the Space that contains the window is visible, but rather the window visibility itself. The same results as in @simonacca experiment

I think the issue can be closed but feel free to keep the discussion if you think that something is off

**Comment by KasselMarc** [comment]
Aerospace has the second highest energy impact among the programs I use, around 73% of my browser (which has the highest energy impact). For a 12h portion activity monitor shows me 340 for Aerospace and 460 for my Browser. This is quite noticeable since I'm on a macbook. Anyone experiencing the same?

**Comment by KasselMarc** [comment]
Here a little comparison between Aerospace's and Amethyst's battery usage in my situation (I'm working with 10 work spaces): Aerospace's battery impact is around 75-80% of that of my most used application which also has the highest battery usage (the battery usage of other applications compared to this is negligible). Amethyst, in contrast, has no noticeable battery impact.

**Comment by KasselMarc** [comment]
> WWDC 2013 https://youtu.be/lyXdH5JjMLI?feature=shared&t=981 (16:21), Apple claimed that energy consumption only happens when the window is visible, so it's not based on whether the Space that contains the window is visible, but rather the window visibility itself. The same results as in @simonacca experiment
> 
> I think the issue can be closed but feel free to keep the discussion if you think that something is off

Maybe this has changed over the years, but my tests definitely don't support this claim. As an experiment I used Aerospace with the default macos workspaces, and the battery usage differed drastically compared to using Aerospace's workspaces. This makes AeroSpace basically  unusable for me.

**Comment by ldelossa** [comment]
@nikitabobko - this is not (or maybe, no longer) the case. 

You can prove this pretty easily. I started a CPU stress test using this site: https://mprep.info/gpu 
I then open activity monitor. 

When safari is running in a different **virtual** workspace then activity monitor, it continues to use about 700% CPU.
Now, if you move safari to a separate macOS, the CPU usage drops off a cliff to basically nothing. 

Maybe at some point, macOS decided to make spaces a core primitive for sleeping an app. Either way, your comments above do not hold currently. 

So while it may be okay for GPU usage, its does not hold the same for CPU usage.
