### ISSUE TITLE
Add support for Monterey

### ISSUE THREAD

**Issue by nrgaig** [nikitabobko/AeroSpace#147]
Hello
I will happy to use AeroSpace and help improve it but currently I'm using macOS Monterey and AeroSpace doesn't support it.
I don't have a Mac that can run newer versions of macOS. So ...

i have thoughts about forking and try to build it on my mac.

Is there any difference between the api used in Monterey and Ventura?

**Comment by nikitabobko** [comment]
Hello!

Of course, feel free to try to port it to Monterey. Can't promise that, but if I like the result, I will merge it

Your entry point is:
1. change deploymentTarget
```diff
diff --git a/LocalPackage/Package.swift b/LocalPackage/Package.swift
index 0f736df..e5feb18 100644
--- a/LocalPackage/Package.swift
+++ b/LocalPackage/Package.swift
@@ -5,7 +5,7 @@ import PackageDescription
 
 let package = Package(
     name: "AeroSpacePackage",
-    platforms: [.macOS(.v13)], /* Runtime support for parameterized protocol types is only available in macOS 13.0.0 or newer
+    platforms: [.macOS(.v12)], /* Runtime support for parameterized protocol types is only available in macOS 13.0.0 or newer
                                   And it specifies deploymentTarget */
     // Products define the executables and libraries a package produces, making them visible to other packages.
     products: [
diff --git a/project.yml b/project.yml
index 3b7a6db..b3329d1 100644
--- a/project.yml
+++ b/project.yml
@@ -22,7 +22,7 @@ targets:
   AeroSpace:
     type: application
     platform: macOS
-    deploymentTarget: "13.0"
+    deploymentTarget: "12.0"
     sources: [src/, docs/config-examples/default-config.toml]
     configFiles:
       Release: .local.xcconfig
```
2. Run `generate.sh`
3. Try to compile it and see what breaks

> Is there any difference between the api used in Monterey and Ventura?

I am aware of two problems:
1. I use SwiftUI to show the tray icon https://github.com/nikitabobko/AeroSpace/blob/main/src/AeroSpaceApp.swift#L37 It needs to be rewritten to NSMenu to run on Monterey. An alternative is to keep using SwiftUI on macOS 13 and higher, and NSMenu on Monterey
2. I use parameterized protocol types. They work only since macOS 13, so this code needs to adapted

**Comment by samueljsb** [comment]
@nrgaig This issue was closed as completed, does that mean you found a way to make Aerospace work on Monterey?

**Comment by nrgaig** [comment]
No. I struggled to implement ventura api with the available for Monterey
