### ISSUE TITLE
Going full screen swaps side by side windows

### ISSUE THREAD

**Issue by tomfran** [nikitabobko/AeroSpace#188]
Hi, I noticed a problem on side by side windows after going full screen with one of them. 

Basically, I started with the video on the left, went full screen, pressed esc, and the original placement swapped.

---

**Initial state**

![Screenshot 2024-03-22 at 18 45 40](https://github.com/nikitabobko/AeroSpace/assets/18344761/7288fc05-2e13-444e-925b-392abe741486)

**Full Screen on the video**

![Screenshot 2024-03-22 at 18 45 48](https://github.com/nikitabobko/AeroSpace/assets/18344761/c4fc0733-3351-4303-b33f-2298bed20985)

**Press esc**

![Screenshot 2024-03-22 at 18 45 56](https://github.com/nikitabobko/AeroSpace/assets/18344761/f425635d-1066-47b9-9600-429f0df84e82)

**Comment by nikitabobko** [comment]
It is by design 

When you fullscreen the window, the window detaches from the tree. When you exit fullscreen, the window attaches back to the tree

When the window attaches back to the tree, we need to find the position where to attach it. The current algorithm is to attach it after the most recently used window in the tree

In general case, after you detach window from the tree, the tree could be changed in an unpredictable way, so when you want to attach the window back, there is such thing as "windows previous position", the tree has changed

In version 0.8.x, AeroSpace didn't detached and attached windows but kept fullscreen windows in the tree. Keeping the windows in the tree leads to phantom "holes" in the tree. See #18

**Comment by tomfran** [comment]
Oh I see, thank you for the quick response!

**Comment by bndkkmn** [comment]
I second this. It's not very nice when you transform your browser to be at a certain position + of a certain size and then lose all that by simply fullscreening a video.
