### ISSUE TITLE
Aerospace seems unable to control the main Steam window?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nikitabobko/AeroSpace#193]
I'm new to Aerospace, but one of the very first times I launch it, it's immediately unable to control half of the windows I have open.

Some of those I am unsurprised by. [The `Console.app` interface](https://www.uaudio.com/blog/console-getting-started/) by Universal Audio for their Apollo consoles ([download](https://help.uaudio.com/hc/en-us/articles/215573823-UAD-Software-Downloads)), for instance, is famously poorly-behaved, with a window that's utterly inaccessible and forces itself into strange shapes and configurations without any user-input. But others, like the [Steam](https://store.steampowered.com/about/download) gaming store, I was more surprised by.

This particular Issue is about Steam specifically; but while I'm at it - is there any known workaround for applications like this that are difficult to control? Elevating the process or anything like that?

**Comment by nikitabobko** [comment]
I think what you faced is that Steam window is floating, you can make it tiled by running `layout tiling` command.

The reason why it's floated is because AeroSpace dialog heuristics detected it as a dialog. All windows without a fullscreen button are floated by default (except for some hardcoded exceptions). Steam shows a maximize button instead of a fullscreen button.

> except for some hardcoded exceptions

Actually, Steam was part of these hardcoded exceptions. AeroSpace specifically tiled windows with `com.valvesoftware.steam` bundle ID https://github.com/nikitabobko/AeroSpace/blob/a20ea2b4578c385a2774cc56360578e049372dce/Sources/AppBundle/tree/MacWindow.swift#L217

I rechecked Steam app and I see that they changed bundled ID to `com.valvesoftware.steam.helper`

I have two things to say:
1. It makes me sad applications as big as Steam just change their bundle ID. It's not the way developers are supposed to use bundle ID :(
2. I think I would like to keep Steam floating and I will remove the hardcoded outdated Steam bundle ID. Steam tends to show these stupid "special offers" dialogs on startup which would normally get detected as dialogs only because they don't have a fullscreen button. But hardcoding Steam bundle ID will make "special offers" dialogs tiling

**Comment by nikitabobko** [comment]
> you can make it tiled by running layout tiling command

If you want to tile Steam windows by default you can use `on-window-detected` callback

```
[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam.helper'
run = 'layout tiling'
```
