### ISSUE TITLE
Unexpected behavior after `move-node-to-monitor`

### ISSUE THREAD

**Issue by sbarrios93** [nikitabobko/AeroSpace#196]
Seems like when running `move-node-to-monitor`, focus stays on the next available windiw of the original workspace. If there are no more windows, Aerospace loses focus of any window.

**I'd expect the focus to stay on the moved window (maybe this is related to #186).**

How to reproduce:

1. If more than one window on the focused workspace
```shell
➜ aerospace list-windows --workspace focused
10885 | WezTerm  | aerospace
10994 | TextEdit | Untitled
~
# with WezTerm as focused window
➜ aerospace move-node-to-monitor next --wrap-around; \
  aerospace list-windows --focused
10994 | TextEdit | Untitled
```

2. If only one window on the focused workspace
```shell
~
➜ aerospace list-windows --workspace focused
10885 | WezTerm | aerospace
~
➜ aerospace move-node-to-monitor next --wrap-around; \
  aerospace list-windows --focused
No window is focused
```

If this is not really what's expected, I'd expect at least to be able to use the `focus` command on a specific window id, so that I could do

1. Get focused windowID
2. move-node-to-monitor
3. focus $windowID

---
Hacky workaround currently, maybe someone finds this useful. I usually only use (at most) 2 monitors, so I'm doing this:
```shell
aerospace move-node-to-monitor next --wrap-around && aerospace focus-monitor next --wrap-around && aerospace list-windows --focused 
```

**Comment by nikitabobko** [comment]
> Seems like when running move-node-to-monitor, focus stays on the next available windiw of the original workspace. If there are no more windows, Aerospace loses focus of any window

It's exactly how it works and it's by design. `move-node-to-monitor` performs one and only one operation - move the window to the target monitor, the command shouldn't change the focused workspace.

You can make focus follow the window by using `focus-monitor` as you described. `focus-monitor` will focus the most recently "used" window on the target monitor, that's why it works.

#186 suggests that there should be a `--focus-follows-window` flag to enable focus-following
