### ISSUE TITLE
Selecting app without switching to that workspace

### ISSUE THREAD

**Issue by caseycronyn** [nikitabobko/AeroSpace#299]
Hello Nikita,

I was wondering is it possible/ what's the best way to select an app without switching to the workspace that app is open in?

For instance if safari is open on workspace 1 and I am on workspace 2, how would I open a new safari window on workspace 2? At the moment what I'm doing is opening on workspace 1, then moving the window to workspace 2, then switching to workspace 2.

Many thanks,
Casey

**Comment by grapexy** [comment]
I believe I have a similar issue. 

I have keepassxc always on ws9, and my browser in ws1, when browser asks keepassxc for credentials, `keepassxc` opens a dialog in ws1 to either allow or deny the request. Clicking anywhere in that dialog (including the buttons) actually sends me to ws9, instead of registering the button click, then I have to move back to ws1 to click again and only then the button click is registed.

**Comment by nikitabobko** [comment]
Will be covered by #186 & #278 

`list-windows --app-bundle-id com.apple.Safari --format %{window-id} | xargs move-node-to-workspace focused --act-on-window-id`
