### ISSUE TITLE
Is it possible to open windows of the same app into accordion even in a tiling setup?

### ISSUE THREAD

**Issue by nekonora** [nikitabobko/AeroSpace#303]
Sorry if this was already asked and/or is trivial but I couldn't find anything by searching the docs or figure out how to do it (if possibile).

Basically I'd like for windows of the same app to stack in an accordion layout whenever a new window is opened. For example:

Before:
```
space 
    - tile app 1
    - tile app 2
    - tile app 3
```

I open a new window of app 3:
```
space 
    - tile app 1
    - tile app 2
    - accordion
        - app 3 
        - app 3
```

Thanks!

**Comment by nikitabobko** [comment]
This is not possible out of the box, and likely will never be possible out of the box unless you (or somebody else) suggest generic and extensible mechanism to make it possible to achieve what you want

What you want looks like a dynamic twm, but not exactly, because you want to layout window based on applications (which dynamic twm usually don't support). I have the mental model in mind on how to support dynamic twm - #260 but the current proposal doesn't support what you want

**Another option.** Once `tree` CLI command is supported #16 (and maybe `on-focus-changed` #230), you could try to script your desired workflow yourself

**My personal opinion.** Treating applications in some special way during window layout is wrong. Window managers should work with "window" objects, not "application" objects. It's well known that people don't like `cmd+tab` in macOS because it works with "apps" not "windows"

**Comment by nekonora** [comment]
Got it, looks like I'll wait for those to be implemented and try to build on that in case I need it. But what you said in the last paragraph make sense actually, I'll try to see how that works. Thanks a lot!
