### ISSUE TITLE
Consider hiding empty workspaces in the menu

### ISSUE THREAD

**Issue by jameschensmith** [nikitabobko/AeroSpace#34]
#### Summary

Version: `AeroSpace v0.5.0-Beta 689fb92db5af7d3ccddf1899e0c00af5930c54dc`

I don't think I'm ever going to be having 36 workspaces simultaneously. Others may, though. It would be nice if the workspaces listed in the menu bar were only the non-empty workspaces. An exception would be switching to an empty workspace to start opening some apps in. In this case, the solution could be to have the workspace shown in the label, and _possibly_ also in the list of workspaces temporarily.

The arguments I could see against this consideration are:
- Decreased visibility of what workspaces exist to choose from.
- Difficulty opening a new workspace via point-and-click method.

**Comment by nikitabobko** [comment]
One more argument for showing all workspaces:
- Debug the config. Since 0.6.0, AeroSpace even shows the workspaces that are mentioned in the `workspace-to-monitor-force-assignment` to make [mistakes in the config](https://github.com/nikitabobko/AeroSpace/issues/19#issuecomment-1819589837) easier to debug

> Difficulty opening a new workspace via point-and-click method

Yes, exactly. Keyboard users don't care about the menu. But mouse users can switch to all workspaces mentioned in the config

**Comment by jameschensmith** [comment]
Yeah, that's fair. With the realization that I could remove the majority of the workspaces from the default configuration, I'm good with you closing this issue as well 👍
