### ISSUE TITLE
Github discussions

### ISSUE THREAD

**Issue by pszypowicz** [nikitabobko/AeroSpace#346]
Hi, first - thank you for this excellent tiling manager!

I'm was thinking, would you consider enabling github discussions for this project?

Sometimes I have a generic question - something which probably other project members already faced and it feel to small to open a github issue for it. 

Thanks in advance!

**Comment by nikitabobko** [comment]
In it's current form, I don't like how GitHub Discussions are implemented. There are use cases for GH discussions, but IMO they don't cover well the use case of "forum"/"community". In particular, I've not seen good examples of active GH discussions communities. Most of the time, it's the place where people ask questions and nobody answers (well, maintainers sometimes do).

One particular example that makes me sad is when i3 migrated from Reddit to GH discussions. You can see how active their subreddit was https://www.reddit.com/r/i3wm/ and how much more silent their GH discussions is https://github.com/i3/i3/discussions. Yes, I know that they migrated because of the Reddit API thing, but the end result is just worse IMO.

In it's current form, GH discussions are merely GH issues, but with (simplified) threads. Given their similarity with issues, enabling discussions might cause more harm than good, because people would need to search in two places.

If there is a need in "forum" or "place to discuss", I think it will emerge naturally itself in a more well suited places like Reddit, Discord, Telegram or whatnot. I myself is not active in either of these platforms and I'm not interested in moderating the forum.

I'm ready to help by linking forums in the README but the forum is either has to be already somewhat active, or backed by people with "positive reputation" (positively active people here in GH issues, posititvely active in the internet or related communities, etc)

Right now, questions can be asked directly in the issues, and the possibility is explicitly stated in the CONTRIBUTING.md

**Comment by pszypowicz** [comment]
I may provide an example of a good discussion space: https://github.com/Hypfer/Valetudo/discussions

"Unfortunately" even they, due to very active community, have dedicated channels on the telegram. 

There is one advantage of having github discussion though - you can convert github issues into it. And in some contexts it make more sense. Like I would really, really want to open a discussion to asks others about their workflows. And usually "issue" indicates that I recognise something as a problem within software - where from the start I know it is not. I'm also wasting your time, mixing valid "issues" it with super low priority questions.

As for non active discussions, I saw them everywhere - reddit/matrix, forums - you name it ;) I'm not sure github is making it any worse. 

And to walk the walk - I may offer help with moderating it :) 

|                               | indexable by google | do not require account to read | require account to write | not a social media with algorithm provided content | ease of moderation |
|-------------------------------|---------------------|--------------------------------|--------------------------|----------------------------------------------------|--------------------|
| github                        | ✅                   | ✅                              | ✅                        | ✅                                                  | ❓                  |
| reddit                        | ✅                   | ✅                              | ✅                        | ❌                                                  | ❓                  |
| slack/discord/telegram/matrix | ❌                   | ❌                              | ✅                        | ✅                                                  | ❓                  |

**Comment by gldtn** [comment]
> I may provide an example of a good discussion space: [Hypfer/Valetudo/discussions](https://github.com/Hypfer/Valetudo/discussions)
> 
> "Unfortunately" even they, due to very active community, have dedicated channels on the telegram.
> 
> There is one advantage of having github discussion though - you can convert github issues into it. And in some contexts it make more sense. Like I would really, really want to open a discussion to asks others about their workflows. And usually "issue" indicates that I recognize something as a problem within software - where from the start I know it is not. I'm also wasting your time, mixing valid "issues" with super low priority questions (and I do not mind if they "stale")
> 
> As for non active discussions, I saw them everywhere - reddit/matrix, forums - you name it ;) I'm not sure github is making it any worse.
> 
> And to walk the walk - I may offer help with moderating it :)
> 
> indexable by google	do not require account to read	require account to write	not a social media with algorithm provided content	ease of moderation
> github	✅	✅	✅	✅	❓
> reddit	✅	✅	✅	❌	❓
> slack/discord/telegram/matrix	❌	❌	✅	✅	❓

+1 on this, I would also be willing to help moderate/help out on the discussions if you change your mind!

**Comment by gservat** [comment]
GitHub Discussions would be great, and it's neat that you can not only convert an issue into a discussion but [go the other way, too](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-discussion).

I've had questions in the past that I'd love to ask (as a newcomer to the project from yabai) but filing an issue doesn't feel right and discussions are ideal for that.

Happy to help with [moderating discussions](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions).

**Comment by nikitabobko** [comment]
GitHub discussions was enabled in the repository
