### ISSUE TITLE
Introduce max-width for nodes

### ISSUE THREAD

**Issue by tobi** [nikitabobko/AeroSpace#368]
Having windows go full-width on large monitors and ultrawides is jarring and undesired. There are a few tickets already on this, but I'd love to contribute my favorite way to solve this. And if the @nikitabobko is willing to merge this, I'm happy to offer a small bounty for the implementation, if that's desired. 

Introduce `default-node-max-width: 1280`. When set, this gives each new node a maximum width when it is created. On a screen that cannot be filled fully due to this constraint, a new window/node is centered with margins to the edges of the screen. I think would be an elegant improvement for the people that are bothered by this, and should introduce minimal amount of additional complexity to the system. Certainly avoids nasty late night, dark mode for hours, accidentally-flashbang-yourself-with-google.com on a 1800nits display problem which inspired this ticket 😅.

Some additional considerations:
- Floating windows are unaffected by this
- Nodes that are not connected to the root-container are unaffected by this
- We introduce a new layout command `layout tiling-fullwidth` that allows for hotkeys that disable the constraint. Example: `ctrl-alt-cmd-space = ['layout tiling-fullwidth tiling']`. Windows in this tiling-fullwidth state just ignore the maxwidth attribute
- The resize function should increase the node's maxwidth if its being resized beyond the current maxwidth's size so a node at 1200px width that gets a 'resize smart +200' sets its internal maxwidth to the new size. This means that moving the node later to another screen retains the session desired maxwidth
- resize should learn to set maxwidth for nodes specifically like `resize max-width 800`, this enables setting some types of windows to be constrained by default like so:
-
  ```
  [[on-window-detected]]
  if.app-id = 'com.googlecode.iterm2'
  run = ['layout tiling', 'resize max-width 800']
  ```
  
 I *think* that this is a horizontal only thing. Maybe there should be a vertical version of this as well, but I have a hard time coming up with a great use-case for this, so maybe best to just skip it.

**Comment by nikitabobko** [comment]
Thanks for sharing your vision!

> default-node-max-width

I'm curious if is it a mistake or is it intentional? The definition of "node" includes windows and containers. Restricting nodes max width will effectively restrict the root container width, which is no different from having big gaps.

My vision was different. I planned to introduce `windows-max-width`, and it would restrict only windows width, leaving containers width flexible. I lean towards restricting windows width because the more windows you have, the bigger becomes the total max width restriction (which should work nicely for the ultrawide monitor use case). Though I just realized that this vision has unfortunate feature interaction with mouse resizing.

---

Another thing is where to store "max width restriction". According to your description, you want to store it in the nodes/windows themselves. This way it's possible to resize nodes/windows independently

My vision was to have as many `windowsMaxWidth` as many monitors there are, and disallow resizing bigger than max width.

Since the primary use case is to improve experience for ultrawide monitors, it feels natural to me that `windowsMaxWidth` is a property of every monitor. And your idea to store "windows max width" in windows themselves isn't yet intuitive to me. 

I understand that "isn't yet intuitive to me" is a bad argument, and I will try add a comment later when I realize it. Maybe my intuition is afraid that every window will now have a property that is not directly observable (which feels too chaotic and random), or maybe it's something different, I didn't realize it yet.

> We introduce a new layout command `layout tiling-fullwidth` that allows for hotkeys that disable the constraint.

What would be the use case for disabling the constraint?

> resize should learn to set maxwidth for nodes specifically like `resize max-width 800`, this enables setting some types of windows to be constrained by default like so:

And I afraid that possibility to set `max-width` for every specific window encourages too much tinkering. I still yet lean more towards "windows max width per monitor" approach.

**Comment by adaviloper** [comment]
If a `window-max-width` is perhaps too restricting, have you considered perhaps providing a way to define layout "zones" in some way.

Something akin to defining proportioned areas that windows would be constrained to. Then you can have multiple proportions for the trees to work in.

For example, you could define multiple zones such as:

```
                                             1/1 
+-------------------------------------------------------------+
|                                                                                                      |
|                                                                                                      |
|                                                                                                      |
|                                                                                                      |
|                                                                                                      |
|                                                                                                      |
+-------------------------------------------------------------+
```

```
                        1/2                                             1/2 
+-------------------------------------------------------------+
|                                                 |                                                    |
|                                                 |                                                    |
|                                                 |                                                    |
|                                                 |                                                    |
|                                                 |                                                    |
|                                                 |                                                    |
+-------------------------------------------------------------+
```

```
          1/4                             1/2                                    1/4 
+-------------------------------------------------------------+
|                        |                                                 |                           |
|                        |                                                 |                           |
|                        |                                                 |                           |
|                        |                                                 |                           |
|                        |                                                 |                           |
|                        |                                                 |                           |
+-------------------------------------------------------------+
```


```
          1/3                             1/3                                    1/3 
+-------------------------------------------------------------+
|                              |                                  |                                    |
|                              |                                  |                                    |
|                              |                                  |                                    |
|                              |                                  |                                    |
|                              |                                  |                                    |
+-------------------------------------------------------------+
```

etc etc

Could help to avoid having to manually calculate any different monitor sizes when switching between stations.

**Comment by tobi** [comment]
> Thanks for sharing your vision!
> 
> > default-node-max-width
> 
> I'm curious if is it a mistake or is it intentional? The definition of "node" includes windows and containers. Restricting nodes max width will effectively restrict the root container width, which is no different from having big gaps.

> My vision was different. I planned to introduce `windows-max-width`, and it would restrict only windows width, leaving containers width flexible. I lean towards restricting windows width because the more windows you have, the bigger becomes the total max width restriction (which should work nicely for the ultrawide monitor use case). Though I just realized that this vision has unfortunate feature interaction with mouse resizing.

I think the question is what we want to happen if the monitor width is larger than twice the max width. The first window will definitely be centered. What happens when the second window is added. Are both windows centered on the screen, or are both windows centered in their nodes, so effectively have a big gap between them? In effect this is the difference between css justify-content: centered or justify-content: space-between. I think strongly that centered is better. 

> Another thing is where to store "max width restriction". According to your description, you want to store it in the nodes/windows themselves. This way it's possible to resize nodes/windows independently
> 
> My vision was to have as many `windowsMaxWidth` as many monitors there are, and disallow resizing bigger than max width.
> 
> Since the primary use case is to improve experience for ultrawide monitors, it feels natural to me that `windowsMaxWidth` is a property of every monitor. And your idea to store "windows max width" in windows themselves isn't yet intuitive to me.

> 
> I understand that "isn't yet intuitive to me" is a bad argument, and I will try add a comment later when I realize it. Maybe my intuition is afraid that every window will now have a property that is not directly observable (which feels too chaotic and random), or maybe it's something different, I didn't realize it yet.

I think the case where the value will be overwritten will be pretty rare, so maybe your intuition is right. I'm thinking that web browsers should be max 1280px for most websites to look good, but sometimes you really want it to be wider using a specific website. This should just be possible without turning off the global setting. 



> 
> > We introduce a new layout command `layout tiling-fullwidth` that allows for hotkeys that disable the constraint.
> 
> What would be the use case for disabling the constraint?

Similar to the above: if you give a presentation in google slides, or are in a video chat that's best looked at full width screen. It would be bad if you have to turn off aerospace because you use a tool that needs the entire screen. 

> > resize should learn to set maxwidth for nodes specifically like `resize max-width 800`, this enables setting some types of windows to be constrained by default like so:
> 
> And I afraid that possibility to set `max-width` for every specific window encourages too much tinkering. I still yet lean more towards "windows max width per monitor" approach.

Totally losing the ability to make any window fullscreen feels challenging in day to day. VSCode flow state sessions, fullscreen presentations, fullscreen youtube video, IA Writer in zen mode, Video games in windowed mode. All those are things I wanted to temporarily use more than 1280px for a window recently. But maybe there is a simpler way to accomplish this?

**Comment by nikitabobko** [comment]
> I think strongly that centered is better.

I agree

> if you give a presentation in google slides, or are in a video chat that's best looked at full width screen. It would be bad if you have to turn off aerospace because you use a tool that needs the entire screen.

I guess it makes sense... I never used an ultrawide monitor, so it's unclear to me how these apps look when they appear super wide. Do you mind attaching a screenshot?

**Comment by tobi** [comment]
don't have a good one as i'm on the road right now. But you can pretty much see the issue in the [review shots of this one](https://www.rtings.com/monitor/reviews/samsung/odyssey-neo-g9-g95na-s49ag95), which is the most common one. For what it's worth, i don't think that's an ultrawide only feature. While maybe not at laptop level- 30" screens would definitely benefit from a max-width cap.

**Comment by druvv** [comment]
> I guess it makes sense... I never used an ultrawide monitor, so it's unclear to me how these apps look when they appear super wide. Do you mind attaching a screenshot?

Here's a good example of Slack when it is super wide. As you can see, reading messages is pretty difficult because my eyes have to scan the entire width of the monitor. For a sense of scale, the horizontal width of my monitor is 32 inches (81 cm).

![Screenshot 2024-08-25 at 5 49 45 PM](https://github.com/user-attachments/assets/045dc5f7-aba8-4302-bf55-b0f397248233)

I've added pretty large outer gaps to compensate, but this isn't great because I lose screen real-estate when tiling multiple windows. Currently, aerospace doesn't completely solve my problem -- but with a max width type like solution it'll be perfect for me.

**Comment by bbrendon** [comment]
The problem is far worse on a 40 inch ultrawide. Also I see other great ideas https://github.com/nikitabobko/AeroSpace/issues/465

**Comment by galligan** [comment]
Just wanted to +1 @tobi's request here, and stay in touch with this issue as it's currently the only thing holding me back from using AeroSpace, which I'm otherwise very excited about.

While some apps do a good job with keeping to reasonable line lengths of roughly 60-75 characters per line, some unfortunately don't make such accommodations—Slack, Spark, Mail.app, and Notes.app being notable examples. This makes using them on a screen like those described very difficult.

In my case, I've got a Pro Display XDR, and seeing windows like Finder, Notes, etc. full screen is jarring and offputting to the point where it's impractical to use them with AeroSpace. #552 would also help out in this instance.

Max width would be a great solution, as in a space where only one window is present, but max width is enforced, the surrounding space would simply be the desktop.

I'll also note that in some cases, perhaps restricted to certain spaces, max height would also be beneficial. That's because with a monitor as large as the Pro Display, keeping my vision centered in the middle is sometimes preferred, and a 100% height window can also be unwieldy.

Love the project so far @nikitabobko and looking forward to being able to use AeroSpace one day!

**Comment by nickcj931** [comment]
> If a `window-max-width` is perhaps too restricting, have you considered perhaps providing a way to define layout "zones" in some way.
> 
> Something akin to defining proportioned areas that windows would be constrained to. Then you can have multiple proportions for the trees to work in.
> 
> For example, you could define multiple zones such as:
> 

Having zones would be amazing as literally Aerosapce is pretty perfect for laptop size screen or non-wide screen displays, however its just shy of being useful for widescreens. And as others have mentioned creates a rather jarring experience.
