### ISSUE TITLE
Issue with lettered workspace switching

### ISSUE THREAD

**Issue by rieger-jared** [nikitabobko/AeroSpace#443]
Hi,

I'm having an issue though with lettered workspaces. Some letters work such as U and M but others such as ASDFXW don't. That means I can't use `alt-s` to open that workspace, nor `alt-shift-s` to move a node to that work space.

Has someone ran into this before?

**I'm not using a custom keyboard. On my Mac I have US Keyboard and input**

I've seen this thread, but it doesn't seem like it's resolved. https://github.com/nikitabobko/AeroSpace/issues/93

I've also tried remapping via `[key-mapping.key-notation-to-key-code]` the standard letters eg `a = 'a'`

Checklist
[x] I've searched for duplicates. My search queries were (please don't forget to search in closed issues too):
- is:issue workspace letters 
- is:issue unable to open certain workspaces 
[x] I've read the documentation https://nikitabobko.github.io/AeroSpace/guide & https://nikitabobko.github.io/AeroSpace/commands
[x] I've searched in the documentation. My search queries were:
- key bindings
- keyboard layouts
- keyboard configurations 
[x] I've also read the following section
https://nikitabobko.github.io/AeroSpace/guide#key-mapping

```version
aerospace CLI client version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
AeroSpace.app server version: 0.14.2-Beta 0cb8dbdfc5ee73b8cbc200f175f467ebead55201
```

**Comment by ivans** [comment]
@rieger-jared I had similar issues with some combinations not working, or breaking usual purpose of keys of my Mac keyboard. In my keyboard layout `alt-2` writes "@" and `alt-n `writes "~". The easies solution for me, the one I also used with Amethyst before was to use `hyper` key and `shift-hyper` combinations instead of `alt` and `shift-alt` (`ctrl-alt-cmd` mapped to `caps-lock` and `ctrl-alt-cmd-shift` mapped to `shift-caps-lock`). This works perfectly and I only wish if problems with key mapping were mentioned more in the documentation, or if there was an easier way of defining the modifier key like you can do with i3.

**Comment by ivans** [comment]
> Hey @ivans, thanks for the reply. OK interesting. Is this something you can solely configure in aerospace config, or something on the OS level?

The only part I did outside aerospace was mapping caps-lock to `ctrl-alt-cmd` using karabiner-elements.

**Comment by ivans** [comment]
@rieger-jared my Mac has a croatian keyboard and I still didn't figure out how to map some of the keys that I want to use (the ones to the right of "0", I have "/" (shift -> "?") and to the right of that "+" (shift -> "*").

Some help handling non US/UK keyboards would be very helpful.

**Comment by nikitabobko** [comment]
Please check that you don't have conflicts with any other software that listens for global keys (e.g. karabiner, skhd, etc)
