### ISSUE TITLE
Adjust windows opacity?

### ISSUE THREAD

**Issue by AurevoirXavier** [nikitabobko/AeroSpace#505]
Thanks for making this great software.

It's more modern, easy-to-use, and elegant than yabai.

The only thing preventing me from switching from yabai to aerospace is the ability to change a window's opacity.

I'm uncertain whether this aligns with the objectives of aerospace.

**Comment by bcremer** [comment]
See
- https://github.com/nikitabobko/AeroSpace/issues/330
- https://github.com/nikitabobko/AeroSpace/issues/452

**Comment by pxeger** [comment]
On Linux I use window transparency all the time, and it is not just an aesthetic feature for me. I can overlay one window (often the one I'm writing in) on top of another (often the one I'm reading from) - then on a laptop with a small screen I find it much nicer than a split view because you can see more stuff at once. So this is my argument that opacity _is_ a practical feature - although I appreciate it's quite niche.

Also the only way I've found to get transparency is with yabai, and that requires disabling SIP for transparency to work (https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection), so maybe it's not even possible to implement while keeping the constraint of not requiring users to disable SIP.
