### ISSUE TITLE
How to build release?

### ISSUE THREAD

**Issue by MatthiasGrandl** [nikitabobko/AeroSpace#75]
So I just tried building AeroSpace myself (to try out the recent CLI commands) and stumbled across a couple of problems:
- `build-docs.sh` uses coreutils cp instead of the default Darwin cp. I'd suggest to add instructions to add `brew install coreutils` and maybe change the uses of `cp` with `gcp`.
- after resolving that issue, running `build-release.sh` throws this error `/Users/matthias/AeroSpace/AeroSpace.xcodeproj: error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "4MWP47XA68" with a private key was found. (in target 'AeroSpace' from project 'AeroSpace')` I guess it would be nice if the team ID could be set with an environment variable.

After adjusting the team ID in the project.yml I was able to build the release. If you want I can create a PR with my proposed changes and add some documentation.

**Comment by nikitabobko** [comment]
> and maybe change the uses of cp with gcp

You can do that but it won't last long. It will last until I write one more script. On my machine, I replaced BSD with GNU https://gist.github.com/skyzyx/3438280b18e4f7c490db8a2a2ca0b9da, and I don't care about BSD

- One option I see is to mention that building the release version may require GNU tools in the document you want to write.
- Another option could be to build the release version on CI for testing that BSD build is not broken. But the problem is that we need to set some team ID on GH actions. I don't want to share my private signature with GH actions. Maybe GH actions has some built-in team ID. If it doesn't then I don't see how it can be done (but I didn't think it thoroughly)

> I guess it would be nice if the team ID could be set with an environment variable.

If xcodegen can do that, it would be nice

> If you want I can create a PR with my proposed changes and add some documentation

It'd be nice, thanks! I'd extract it into a separate document like `docs/development.md` and mention it in the readme. "How to build the project" and "How to run the tests" sections of the readme can be moved to the newly introduced document

---

I'm curious: if it's for testing, why building the debug version didn't work for you? `run-debug.sh` would do the trick. The debug is built on GH actions, so it's checked that it is compatible with BSD

**Comment by MatthiasGrandl** [comment]
The debug build did work indeed without coreutils, but I didn’t understand how to make it use my existing AeroSpace config. Probably would have been the easier solution :)

**Comment by nikitabobko** [comment]
> but I didn’t understand how to make it use my existing AeroSpace config

The debug build uses `~/.aerospace-debug.toml`

**Comment by MatthiasGrandl** [comment]
Ok perfect, then I'll just use the debug build in the future 👍
