### ISSUE TITLE
`default-root-container-layout = 'accordion'` not honored for workspace 1

### ISSUE THREAD

**Issue by veyga** [nikitabobko/AeroSpace#775]
**Describe the bug**
The `accordion` root container layout doesn't appear to be honored, but only for `workspace 1`; it defaults to `tiles`. The accordion layout as a default root works as expected in other workspaces.

Here are the relevant configs which can be used to reproduce:
```
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'
```

I have tried with/without normalization as well as vertical and horizontal orientations; the issue persists.

Versions:
```
aerospace CLI client version: 0.16.0-Beta d172dfd8a92f2d339f3d46a12a297e43e80768ca
AeroSpace.app server version: 0.16.0-Beta d172dfd8a92f2d339f3d46a12a297e43e80768ca
```

macOS version: Sequoia 15.1.1

**Comment by nikitabobko** [comment]
Insufficient details

**Comment by z0al** [comment]
I have the opposite situation where `default-root-container-layout = 'tiles'` isn't honored. It's reproducible every time I click "Quit Aerospace" and start it again, it starts in stacked/accordion mode. This has been the case for a while now.

@nikitabobko what kind of details are needed to warrant an investigation? The [issue template](https://github.com/nikitabobko/AeroSpace/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) doesn't ask a lot of questions.

**Comment by nikitabobko** [comment]
@z0al your case is different. When you launch AeroSpace and more than 3 windows get scheduled on the focused workspace (e.g. you can use `on-window-detected` to schedule windows on different workspaces), AeroSpace will switch the layout to accordion.

It happens only on startup to make onboarding experience better, because if there are too many windows open, `tiles` layout doesn't look that good because of min-width window restriction, and it may scare off new users.

As a workaround, you can cancel the effect of this "smart" behavior

```toml
after-startup-command = ['layout tiles']
```

I agree that it's not perfect, but I don't care enough to think of a better solution.

**Comment by z0al** [comment]
That works. Thank you @nikitabobko . I agree slapping that one line is good enough.
