### ISSUE TITLE
Remember Monitor for Window Position even after sleep or shutdown

### ISSUE THREAD

**Issue by akbar-mirza** [nikitabobko/AeroSpace#888]
When using a 3-monitor setup with Aerospace on macOS, window positions reset after the Mac goes to sleep. This requires manual adjustments to restore windows to their previous positions, disrupting workflow efficiency. A feature to remember and restore window positions for each monitor would greatly enhance user experience.

**Comment by nikitabobko** [comment]
Window positions should already be preserved when Mac goes to sleep or you lock the screen. If they are not, it's a bug

Unfortunately, when you lock the screen, windows become almost indistinguishable from dead windows, so sometimes AeroSpace may think that all/some windows were closed when you lock the screen, and when you unlock the scren, AeroSpace just tiles them as new, fresh windows. Right now, AeroSpace applies some heuristics to distinguish dead windows from "locked screen". Sometimes these heuristics could not be precise enough and cause false positive situations (like in your case).

For me, the heuristics work good enough. I have never seen all apps to merge into the focused workspace when I unlock my screen. I occasionally (maybe once a week or two) observe that 1 window may jump to the focused workspace during unlock.

In previous versions, the detection mechanism was different, and it was problematic in another way. It could be false negaitve causing ghosts windows #445. I had to change it because of that. I bet that if you try 0.15.2 the bug will go away for you.

I also bet that it's false positive in your case because of your environment (some specific applications cause false positive, your monitor count, or "Displays have separate Spaces" in System Settings). It would be helpful if you could minimize your report (try to reduce monitor count and see if the problem goes away, pin-point the problem to specific apps, etc.) and create a bug report with the specifics, thanks
