### ISSUE TITLE
Doesn't seem to respect keyboard layout

### ISSUE THREAD

**Issue by Nikki1993** [nikitabobko/AeroSpace#93]
I am running Dvorak layout but it appears keybinds are executed as if I am running QWERTY layout. Is there a possibility to make AeroSpace respect keyboard layout set or do I have to rebind all keys in such a way that when I press ALT+R (Dvorak) it will execute ALT+O (QWERTY) keybind?

**Comment by nikitabobko** [comment]
I'm not a Dvorak user, so I can't help you with that, sorry.

The only guidance I can give is that AeroSpace uses https://github.com/soffes/HotKey dependency to manage global keys. I managed to find this issue in their repo https://github.com/soffes/HotKey/issues/2, it looks like the problem you mention

Frankly speaking, the experience with HotKey library wasn't smooth during the development, plus the HotKey library [doesn't support left/right modifiers](https://github.com/nikitabobko/AeroSpace/issues/28), and AeroSpace [has random bugs with hotkeys handling](https://github.com/nikitabobko/AeroSpace/issues/46)

Maybe I'm using the library incorrectly, but whatever.

I want to try to replace this dependency with something else and see how it goes. Hopefully, it will fix the Dvorak issue

**Comment by hrvstr** [comment]
It's even worse for German keyboard layouts. When mapping keys I have to keep an image of a US keyboard open. So when I see in the config:

```
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
```

The app is actually listening on `alt-shift-questionmark`and `alt-shift-backtick`.

**Comment by ELLIOTTCABLE** [comment]
I saw the work on this, but it looks like you force-pushed over it 😅

Any chance we could get a testing-release with the fix?

**Comment by nikitabobko** [comment]
0.9.0 addresses the issue. See https://nikitabobko.github.io/AeroSpace/guide#key-mapping

The project now also accepts funding https://github.com/sponsors/nikitabobko

**Comment by nikitabobko** [comment]
Elaboration

Apple API speaks in terms of key-codes. Key-code `q` is a key next to the `tab` key. If we wanted to automatically support layouts, then we'd need to subscribe for keyboard layouts changes (if Apple provides an API for it). When the keyboard layout changes, we'd need to translate key notations to key codes (if Apple provides an API for it), and "remap" our subscriptions for key codes

And I don't even want to think what happens with non-Latin layouts, or when users have several Latin layouts

There are so many places where anything can go wrong with an automatic approach. That's why I think, it's more reliable to give users a way to remap keys manually

Apparently, skhd resolved these issues somehow, but I'm not going through this rabbit hole

**Comment by eproxus** [comment]
(Let me know if I should open a new issue for this)

Thanks for a great tool!

I'm trying to get `alt-slash` to work on a custom Dvorak layout and it just doesn't seem to trigger. <kbd>Alt</kbd>+<kbd>/</kbd> works fine in Hammerspoon, but AeroSpace doesn't recognize it. In an editor, if I press <kbd>Alt</kbd>+<kbd>/</kbd> a `÷` is inserted (because that is how the keyboard layout is defined) but many other programs detects it properly.

Are there plans to fix issues like these in AeroSpace or are they effectively closed as "wont fix"?

I'll try to see if I can combine it with skhd but it would be great if it worked out of the box.

**Comment by lknop** [comment]
I would go with skhd. Aerospace is using a high-level api and gets the keycodes it gets. Without migrating to a different hotkey library this issue is likely unsolveable. If other software is able to match the keys for you I think it's safer to use it rather than rewriting that part of aerospace.
